<?php

namespace Tests\Unit;

use App\Http\Controllers\BookController;
use App\Models\Book;
use PHPUnit\Framework\TestCase;

class BookControllerTest extends TestCase
{

    private  $controller;
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->controller = new BookController();


    }

    /**
     * A basic unit test example.
     *
     * @return void
     */


    public function testCreateBook()
    {

        $this->controller->createBook();

    }
}
